name: auto-task-bot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'  # 每天 UTC 12:00 执行

jobs:
  bing-search:
    runs-on: ubuntu-latest
    env:
      BING_COOKIES: ${{ secrets.BING_COOKIES }}
      CHROME_BIN: /usr/bin/chromium-browser
      CHROMEDRIVER_PATH: /usr/bin/chromedriver

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Chromium & Chromedriver
        run: |
          sudo apt update
          sudo apt install -y chromium-browser chromium-chromedriver

      - name: Run BingSearchPoints
        run: python -m core.BingSearchPoints.main

      - name: Run wyycg-autocheckin
        run: python -m core.wyycg_autocheckin.main
