name: pre-commit-bot

on:
  push:
    branches:
      - '**'
    tags:
      - '*'
  workflow_dispatch:

jobs:
  update-reqs:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install project dependencies
        run: |
          pip install -r requirements.txt || true
          pip install pipreqs

      - name: Generate requirements.txt
        run: pipreqs . --force --ignore __pycache__
            
      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "chore: auto update requirements.txt"
          add: "requirements.txt"
          push: true
