name: run_bing_search_points

on:
  workflow_dispatch:  # 手动触发
  schedule:
    - cron: "0 2 * * *"  # 每天 UTC+0 2点执行

jobs:
  search:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Chrome & Chromedriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          pip install selenium

      - name: Run search script
        run: python BingSearchPoints/main.py
